Heal:
  Item: 280
  Data: 0
  GlobalRequirements:
    Perms:
      Type: "Permission"
      Value: "something.something"
      Deny:
      - "[PlayerMessage] You don't have the global permission"

  SubActions:
    RRR:
      Executables:
      - "[PlayerCommand] &4Testing of hi lolll"
      - "[ConsoleCommand] give Flockshot stick"
      - "[PlayerCommand] msg flockshot hi"
      Requirements:
        Perms:
          Type: "Permission"
          Value: "something.else"
          Deny:
          - "[PlayerCommand] msg Flockshot testing perm not work?"
          - "[PlayerMessage] permission else is not there"
          - "[PlayerMessage] yes if this is also enchant than what I said gets true"
        Cooldown:
          Type: "Cooldown"
          Value: "20s"
          Deny:
          - "[PlayerMessage] Cooldown left lol %cooldown_left%"
        Greater:
          Type: ">="
          Value: 42
          CompareWith: 42
          Deny:
          - "[PlayerMessage] 23>=42 not lol??"
        StringEqual:
          Type: String Equals
          Value: "This"
          CompareWith: "This"
          Deny:
          - "[PlayerMessage] String not equal"
        StringEqualIgnoreCase:
          Type: String Equals Ignorecase
          Value: "This"
          CompareWith: "this"
          Deny:
          - "[PlayerMessage] String not equal ignorecase"
        HaveEnchant:
          Type: Enchant
          Value: DURABILITY:3
          Deny:
          - "[PlayerMessage] Enchant is not on the item"    
#/give @p skull 1 3 {display:{Name:"Discord"},SkullOwner:{Id:"de431cd1-ae1d-49f6-9339-a96daeacc32b",
#Properties:{textures:[{Value:"eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNzg3M2MxMmJmZmI1MjUxYTBiODhkNWFlNzVjNzI0N2NiMzlhNzVmZjFhODFjYmU0YzhhMzliMzExZGRlZGEifX19"}]}}}